###Import Modules

In [ ]:
# INSTALL standard libraries not already in Google Colab
!pip install pymysql
# INSTALL custom libraries 
!wget -nc https://github.com/uscprofessor/itp487_enterprise_data_analytics/raw/main/py/itp487helper.py
 
# IMPORT Python packages (standard or must be installed)
import pandas as pd    # main data package
import os
import pymysql         # connects to mysql database
import time            # used to calculate elapsed time
import itp487helper    # ITP 487 helper functions to hide python complexities

Requirement already satisfied: pymysql in /usr/local/lib/python3.7/dist-packages (1.0.2)
File ‘itp487helper.py’ already there; not retrieving.

###Load Raw Data

In [ ]:
# IMPORT NBA Stats data set from github - originally downloaded from Advanced Analytics Systems
!wget -nc https://github.com/uscprofessor/itp487_enterprise_data_analytics/raw/main/data/nba_stats_2020_21.csv 

# LOAD NBA Stats data - orginally from Advanced Sports Analytics
nba_stats_raw = pd.read_csv('nba_stats_2020_21.csv', delimiter=",")

File ‘nba_stats_2020_21.csv’ already there; not retrieving.

###Clean Data

In [ ]:
# CHECK SHAPE
print(nba_stats_raw.shape) # 69 columns and 39891 rows

(42118, 81)

In [ ]:
# VIEW SAMPLE OF DATA
nba_stats_raw.head(10) # view first 10 rows

        game_id   game_date  OT H_A  ...   SF%   PF%     C%  active_position_minutes
0  202012220BRK  2020-12-22   0   A  ...  47.0  51.0    3.0                      NaN
1  202012220BRK  2020-12-22   0   A  ...   0.0   0.0    0.0                      NaN
2  202012220BRK  2020-12-22   0   A  ...  40.0  25.0    2.0                      NaN
3  202012220BRK  2020-12-22   0   A  ...   0.0   0.0  100.0                      NaN
4  202012220BRK  2020-12-22   0   A  ...   2.0  33.0   65.0                      NaN
5  202012220BRK  2020-12-22   0   A  ...   1.0   0.0    0.0                      NaN
6  202012220BRK  2020-12-22   0   A  ...  14.0   3.0    0.0                      NaN
7  202012220BRK  2020-12-22   0   A  ...  47.0  12.0    1.0                      NaN
8  202012220BRK  2020-12-22   0   A  ...   0.0   9.0   91.0                      NaN
9  202012220BRK  2020-12-22   0   A  ...  36.0   3.0    0.0                      NaN

[10 rows x 81 columns]

In [ ]:
# CHECK FOR DUPLICATES
df_dupes = nba_stats_raw[nba_stats_raw.duplicated()]
df_dupes

            game_id   game_date  OT  ...  PF%     C%  active_position_minutes
1009   202012300BRK  2020-12-30   0  ...  0.0    0.0               240.989667
1034   202101010BRK  2021-01-01   0  ...  0.0    0.0               188.789417
1059   202101030BRK  2021-01-03   0  ...  0.0    0.0               175.930111
1082   202101050BRK  2021-01-05   0  ...  0.0    0.0               169.362992
1103   202101200CLE  2021-01-20   2  ...  0.0    0.0               210.230914
...             ...         ...  ..  ...  ...    ...                      ...
40265  202105130PHO  2021-05-13   0  ...  0.0  100.0                88.220303
40273  202105150SAS  2021-05-15   0  ...  0.0    0.0               217.679780
40291  202105150SAS  2021-05-15   0  ...  0.0  100.0                95.045601
40299  202105160SAS  2021-05-16   0  ...  0.0    0.0               218.452187
40317  202105160SAS  2021-05-16   0  ...  0.0  100.0               103.353550

[2227 rows x 81 columns]

In [ ]:
# YES, WE HAVE DUPLICATES
# REMOVE DUPLICATE ROWS
nba_stats = nba_stats_raw.drop_duplicates()  #creates a new DF

In [ ]:
# CHECK COLUMNS W/ NaN VALUES
# DOES ANY COLUMNS HAVE NaN?
nanlist = nba_stats.columns[nba_stats.isna().any()].tolist()
nanlist

['Inactives',
 'DKP_per_minute',
 'FDP_per_minute',
 'SDP_per_minute',
 'pf_per_minute',
 'last_60_minutes_per_game_starting',
 'last_60_minutes_per_game_bench',
 'PG%',
 'SG%',
 'SF%',
 'PF%',
 'C%',
 'active_position_minutes']

###Integrate Data (only if needed)

###Analyze Data

###Publish

In [ ]:
f